// This file is automatically generated by tools/code_gen.c
// Please do not edit it directly

#ifndef EOLIB_LUA_PROTOCOL_H
#define EOLIB_LUA_PROTOCOL_H

#include <lua.h>

void lua_protocol_register(lua_State *L, int module_idx);

#endif /* EOLIB_LUA_PROTOCOL_H */
