#if defined(_WIN32)
#define _CRT_SECURE_NO_WARNINGS
#endif

#include "code_gen_utils.h"

#include <errno.h>
#include <ctype.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

const char *CODEGEN_WARNING =
    "// This file is automatically generated by tools/code_gen.c\n"
    "// Please do not edit it directly\n\n";

int eolib_mkdir(const char *path)
{
#if defined(_WIN32)
    return _mkdir(path);
#else
    return mkdir(path, 0755);
#endif
}

void *xmalloc(size_t size)
{
    void *ptr = malloc(size);
    if (!ptr)
    {
        fprintf(stderr, "Out of memory\n");
        exit(1);
    }
    return ptr;
}

char *xstrdup(const char *value)
{
    if (!value)
    {
        return NULL;
    }
    char *dup = strdup(value);
    if (!dup)
    {
        fprintf(stderr, "Out of memory\n");
        exit(1);
    }
    return dup;
}

void element_list_push(ElementList *list, StructElement element)
{
    if (list->elements_count >= list->elements_capacity)
    {
        list->elements_capacity = ARRAY_GROW_CAPACITY(list->elements_capacity);
        list->elements =
            realloc(list->elements, list->elements_capacity * sizeof(StructElement));
        if (!list->elements)
        {
            fprintf(stderr, "Out of memory\n");
            exit(1);
        }
    }
    list->elements[list->elements_count++] = element;
}

void enum_values_push(EnumDef *def, EnumValue value)
{
    if (def->values_count >= def->values_capacity)
    {
        def->values_capacity = ARRAY_GROW_CAPACITY(def->values_capacity);
        def->values = realloc(def->values, def->values_capacity * sizeof(EnumValue));
        if (!def->values)
        {
            fprintf(stderr, "Out of memory\n");
            exit(1);
        }
    }
    def->values[def->values_count++] = value;
}

void protocol_enums_push(ProtocolDef *protocol, EnumDef def)
{
    if (protocol->enums_count >= protocol->enums_capacity)
    {
        protocol->enums_capacity = ARRAY_GROW_CAPACITY(protocol->enums_capacity);
        protocol->enums =
            realloc(protocol->enums, protocol->enums_capacity * sizeof(EnumDef));
        if (!protocol->enums)
        {
            fprintf(stderr, "Out of memory\n");
            exit(1);
        }
    }
    protocol->enums[protocol->enums_count++] = def;
}

void protocol_structs_push(ProtocolDef *protocol, StructDef def)
{
    if (protocol->structs_count >= protocol->structs_capacity)
    {
        protocol->structs_capacity = ARRAY_GROW_CAPACITY(protocol->structs_capacity);
        protocol->structs =
            realloc(protocol->structs, protocol->structs_capacity * sizeof(StructDef));
        if (!protocol->structs)
        {
            fprintf(stderr, "Out of memory\n");
            exit(1);
        }
    }
    protocol->structs[protocol->structs_count++] = def;
}

void protocol_packets_push(ProtocolDef *protocol, PacketDef def)
{
    if (protocol->packets_count >= protocol->packets_capacity)
    {
        protocol->packets_capacity = ARRAY_GROW_CAPACITY(protocol->packets_capacity);
        protocol->packets =
            realloc(protocol->packets, protocol->packets_capacity * sizeof(PacketDef));
        if (!protocol->packets)
        {
            fprintf(stderr, "Out of memory\n");
            exit(1);
        }
    }
    protocol->packets[protocol->packets_count++] = def;
}

void switch_cases_push(SwitchDef *sw, CaseDef def)
{
    if (sw->cases_count >= sw->cases_capacity)
    {
        sw->cases_capacity = ARRAY_GROW_CAPACITY(sw->cases_capacity);
        sw->cases = realloc(sw->cases, sw->cases_capacity * sizeof(CaseDef));
        if (!sw->cases)
        {
            fprintf(stderr, "Out of memory\n");
            exit(1);
        }
    }
    sw->cases[sw->cases_count++] = def;
}

void string_list_push(StringList *list, const char *value)
{
    if (!value || value[0] == '\0')
    {
        return;
    }
    for (size_t i = 0; i < list->count; ++i)
    {
        if (strcmp(list->items[i], value) == 0)
        {
            return;
        }
    }
    if (list->count >= list->capacity)
    {
        list->capacity = ARRAY_GROW_CAPACITY(list->capacity);
        list->items = realloc(list->items, list->capacity * sizeof(char *));
        if (!list->items)
        {
            fprintf(stderr, "Out of memory\n");
            exit(1);
        }
    }
    list->items[list->count++] = xstrdup(value);
}

int string_list_contains(const StringList *list, const char *value)
{
    if (!list || !value)
    {
        return 0;
    }
    for (size_t i = 0; i < list->count; ++i)
    {
        if (strcmp(list->items[i], value) == 0)
        {
            return 1;
        }
    }
    return 0;
}

void string_list_free(StringList *list)
{
    if (!list)
        return;
    for (size_t i = 0; i < list->count; ++i)
        free(list->items[i]);
    free(list->items);
    list->items = NULL;
    list->count = 0;
    list->capacity = 0;
}

void enum_list_push(EnumDef **list, size_t *count, size_t *capacity, const EnumDef *def)
{
    if (*count >= *capacity)
    {
        *capacity = ARRAY_GROW_CAPACITY(*capacity);
        *list = realloc(*list, (*capacity) * sizeof(EnumDef));
        if (!*list)
        {
            fprintf(stderr, "Out of memory\n");
            exit(1);
        }
    }
    (*list)[*count] = *def;
    *count += 1;
}

void struct_list_push(StructDef **list, size_t *count, size_t *capacity,
                      const StructDef *def)
{
    if (*count >= *capacity)
    {
        *capacity = ARRAY_GROW_CAPACITY(*capacity);
        *list = realloc(*list, (*capacity) * sizeof(StructDef));
        if (!*list)
        {
            fprintf(stderr, "Out of memory\n");
            exit(1);
        }
    }
    (*list)[*count] = *def;
    *count += 1;
}

int path_is_dir(const char *path)
{
    struct stat st;
    if (stat(path, &st) != 0)
    {
        return 0;
    }
    return (st.st_mode & S_IFDIR) != 0;
}

int path_exists(const char *path)
{
    struct stat st;
    return stat(path, &st) == 0;
}

void string_list_push_unique(StringList *paths, const char *value)
{
    if (!string_list_contains(paths, value))
    {
        string_list_push(paths, value);
    }
}

void list_subdirs(const char *base_path, StringList *out)
{
#if defined(_WIN32)
    char search[EOLIB_PATH_MAX];
    WIN32_FIND_DATAA data;
    HANDLE handle;

    snprintf(search, sizeof(search), "%s\\*", base_path);
    handle = FindFirstFileA(search, &data);
    if (handle == INVALID_HANDLE_VALUE)
    {
        return;
    }

    do
    {
        const char *name = data.cFileName;
        if (strcmp(name, ".") == 0 || strcmp(name, "..") == 0)
        {
            continue;
        }
        if (data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)
        {
            char path[EOLIB_PATH_MAX];
            snprintf(path, sizeof(path), "%s/%s", base_path, name);
            string_list_push_unique(out, path);
        }
    } while (FindNextFileA(handle, &data) != 0);

    FindClose(handle);
#else
    DIR *dir = opendir(base_path);
    if (!dir)
    {
        return;
    }

    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL)
    {
        if (strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0)
        {
            continue;
        }

        char path[EOLIB_PATH_MAX];
        snprintf(path, sizeof(path), "%s/%s", base_path, entry->d_name);
        if (path_is_dir(path))
        {
            string_list_push_unique(out, path);
        }
    }
    closedir(dir);
#endif
}

void append_glob_results(StringList *paths, const char *pattern)
{
#if defined(_WIN32)
    if (strcmp(pattern, "eo-protocol/xml/protocol.xml") == 0)
    {
        if (path_exists(pattern))
        {
            string_list_push_unique(paths, pattern);
        }
        return;
    }

    if (strcmp(pattern, "eo-protocol/xml/*/protocol.xml") == 0)
    {
        StringList dirs = {0};
        list_subdirs("eo-protocol/xml", &dirs);
        for (size_t i = 0; i < dirs.count; ++i)
        {
            char path[EOLIB_PATH_MAX];
            snprintf(path, sizeof(path), "%s/protocol.xml", dirs.items[i]);
            if (path_exists(path))
            {
                string_list_push_unique(paths, path);
            }
        }
        return;
    }

    if (strcmp(pattern, "eo-protocol/xml/*/*/protocol.xml") == 0)
    {
        StringList level_one = {0};
        list_subdirs("eo-protocol/xml", &level_one);
        for (size_t i = 0; i < level_one.count; ++i)
        {
            StringList level_two = {0};
            list_subdirs(level_one.items[i], &level_two);
            for (size_t j = 0; j < level_two.count; ++j)
            {
                char path[EOLIB_PATH_MAX];
                snprintf(path, sizeof(path), "%s/protocol.xml", level_two.items[j]);
                if (path_exists(path))
                {
                    string_list_push_unique(paths, path);
                }
            }
        }
        return;
    }
#else
    glob_t matches;
    memset(&matches, 0, sizeof(matches));
    if (glob(pattern, GLOB_TILDE, NULL, &matches) == 0)
    {
        for (size_t i = 0; i < matches.gl_pathc; ++i)
        {
            string_list_push_unique(paths, matches.gl_pathv[i]);
        }
    }
    globfree(&matches);
#endif
}

static const char *c_keywords[] = {
    "auto", "break", "case", "char", "const", "continue", "default",
    "do", "double", "else", "enum", "extern", "float", "for",
    "goto", "if", "inline", "int", "long", "register", "restrict",
    "return", "short", "signed", "sizeof", "static", "struct", "switch",
    "typedef", "union", "unsigned", "void", "volatile", "while", "_Bool",
    "_Complex", "_Imaginary"};

static int is_c_keyword(const char *value)
{
    for (size_t i = 0; i < sizeof(c_keywords) / sizeof(c_keywords[0]); ++i)
    {
        if (strcmp(value, c_keywords[i]) == 0)
        {
            return 1;
        }
    }
    return 0;
}

char *sanitize_identifier(const char *value)
{
    if (!value)
    {
        return xstrdup("_");
    }

    size_t len = strlen(value);
    char *out = xmalloc(len * 2 + 2);
    size_t out_len = 0;

    if (value[0] >= '0' && value[0] <= '9')
    {
        out[out_len++] = '_';
    }

    for (size_t i = 0; i < len; ++i)
    {
        char ch = value[i];
        if ((ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
            (ch >= '0' && ch <= '9') || ch == '_')
        {
            out[out_len++] = ch;
        }
        else
        {
            out[out_len++] = '_';
        }
    }

    out[out_len] = '\0';
    if (is_c_keyword(out))
    {
        char *prefixed = xmalloc(out_len + 3);
        snprintf(prefixed, out_len + 3, "_%s", out);
        free(out);
        return prefixed;
    }

    return out;
}

char *to_snake_case(const char *value)
{
    if (!value)
    {
        return xstrdup("_");
    }

    size_t len = strlen(value);
    char *out = xmalloc(len * 2 + 2);
    size_t out_len = 0;

    for (size_t i = 0; i < len; ++i)
    {
        char ch = value[i];
        if (ch >= 'A' && ch <= 'Z')
        {
            if (i > 0 && out[out_len - 1] != '_')
            {
                out[out_len++] = '_';
            }
            out[out_len++] = (char)(ch - 'A' + 'a');
        }
        else if (ch == '-' || ch == ' ')
        {
            if (out_len > 0 && out[out_len - 1] != '_')
            {
                out[out_len++] = '_';
            }
        }
        else
        {
            out[out_len++] = ch;
        }
    }

    out[out_len] = '\0';
    char *sanitized = sanitize_identifier(out);
    free(out);
    return sanitized;
}

char *to_upper_snake(const char *value)
{
    char *snake = to_snake_case(value);
    for (size_t i = 0; snake[i]; ++i)
    {
        if (snake[i] >= 'a' && snake[i] <= 'z')
        {
            snake[i] = (char)(snake[i] - 'a' + 'A');
        }
    }
    return snake;
}

char *to_pascal_case(const char *snake)
{
    if (!snake)
        return xstrdup("");
    size_t len = strlen(snake);
    char *out = xmalloc(len + 2);
    size_t out_len = 0;
    int capitalize = 1;
    for (size_t i = 0; i < len; ++i)
    {
        char ch = snake[i];
        if (ch == '_')
        {
            capitalize = 1;
        }
        else if (capitalize)
        {
            out[out_len++] = (char)(ch >= 'a' && ch <= 'z' ? ch - 'a' + 'A' : ch);
            capitalize = 0;
        }
        else
        {
            out[out_len++] = ch;
        }
    }
    out[out_len] = '\0';
    return out;
}

char *normalize_path(const char *path)
{
    size_t len = strlen(path);
    char *out = xmalloc(len + 1);
    for (size_t i = 0; i < len; ++i)
    {
        char ch = path[i];
        out[i] = ch == '\\' ? '/' : ch;
    }
    out[len] = '\0';
    return out;
}

char *relative_protocol_dir(const char *path)
{
    char *normalized = normalize_path(path);
    const char *needle = "/eo-protocol/xml/";
    char *pos = strstr(normalized, needle);
    if (!pos)
    {
        free(normalized);
        return xstrdup("");
    }
    pos += strlen(needle);
    char *last_slash = strrchr(pos, '/');
    if (!last_slash)
    {
        free(normalized);
        return xstrdup("");
    }
    size_t len = (size_t)(last_slash - pos);
    char *out = xmalloc(len + 1);
    memcpy(out, pos, len);
    out[len] = '\0';
    free(normalized);
    return out;
}

int ensure_dir(const char *path)
{
    char temp[1024];
    size_t len = strlen(path);
    if (len >= sizeof(temp))
    {
        return -1;
    }
    snprintf(temp, sizeof(temp), "%s", path);
    if (temp[len - 1] == '/')
    {
        temp[len - 1] = '\0';
    }

    for (char *p = temp + 1; *p; ++p)
    {
        if (*p == '/')
        {
            *p = '\0';
            if (eolib_mkdir(temp) != 0 && errno != EEXIST)
            {
                return -1;
            }
            *p = '/';
        }
    }

    if (eolib_mkdir(temp) != 0 && errno != EEXIST)
    {
        return -1;
    }
    return 0;
}

void list_json_files_in_dir(const char *dir_path, StringList *out)
{
#if defined(_WIN32)
    char search[EOLIB_PATH_MAX];
    WIN32_FIND_DATAA data;
    HANDLE handle;
    snprintf(search, sizeof(search), "%s\\*.json", dir_path);
    handle = FindFirstFileA(search, &data);
    if (handle == INVALID_HANDLE_VALUE)
        return;
    do
    {
        if (!(data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY))
        {
            char path[EOLIB_PATH_MAX];
            snprintf(path, sizeof(path), "%s/%s", dir_path, data.cFileName);
            string_list_push_unique(out, path);
        }
    } while (FindNextFileA(handle, &data) != 0);
    FindClose(handle);
#else
    DIR *dir = opendir(dir_path);
    if (!dir)
        return;
    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL)
    {
        const char *name = entry->d_name;
        size_t name_len = strlen(name);
        if (name_len <= 5 || strcmp(name + name_len - 5, ".json") != 0)
            continue;
        char path[EOLIB_PATH_MAX];
        snprintf(path, sizeof(path), "%s/%s", dir_path, name);
        string_list_push_unique(out, path);
    }
    closedir(dir);
#endif
}

void write_doc_comment(FILE *out, const char *comment, const char *indent)
{
    if (!comment || comment[0] == '\0')
    {
        return;
    }
    char *copy = xstrdup(comment);
    char *line = strtok(copy, "\n");
    fprintf(out, "%s/**\n", indent);
    while (line)
    {
        char *start = line;
        while (*start && isspace((unsigned char)*start))
        {
            start++;
        }
        char *end = start + strlen(start);
        while (end > start && isspace((unsigned char)*(end - 1)))
        {
            end--;
        }
        *end = '\0';
        if (start[0] != '\0')
        {
            fprintf(out, "%s * %s\n", indent, start);
        }
        line = strtok(NULL, "\n");
    }
    fprintf(out, "%s */\n", indent);
    free(copy);
}

void write_lua_doc_comment(FILE *f, const char *comment)
{
    if (!comment || comment[0] == '\0') return;
    char *copy = xstrdup(comment);
    char *line = strtok(copy, "\n");
    while (line)
    {
        char *start = line;
        while (*start && isspace((unsigned char)*start)) start++;
        char *end = start + strlen(start);
        while (end > start && isspace((unsigned char)*(end - 1))) end--;
        *end = '\0';
        if (start[0] != '\0')
            fprintf(f, "--- %s\n", start);
        line = strtok(NULL, "\n");
    }
    free(copy);
}

void write_escaped_c_string(FILE *f, const char *s)
{
    fputc('"', f);
    for (; *s; ++s)
    {
        switch (*s)
        {
        case '"':
            fputs("\\\"", f);
            break;
        case '\\':
            fputs("\\\\", f);
            break;
        case '\n':
            fputs("\\n", f);
            break;
        case '\r':
            fputs("\\r", f);
            break;
        case '\t':
            fputs("\\t", f);
            break;
        default:
            fputc(*s, f);
            break;
        }
    }
    fputc('"', f);
}

void write_byte_array_literal(FILE *f, const uint8_t *data, size_t len)
{
    fprintf(f, "{");
    for (size_t i = 0; i < len; ++i)
    {
        if (i > 0)
            fprintf(f, ", ");
        fprintf(f, "0x%02x", data[i]);
    }
    fprintf(f, "}");
}

void write_switch_pragma_push(FILE *f)
{
    fprintf(f,
        "#if defined(__clang__)\n"
        "    #pragma clang diagnostic push\n"
        "    #pragma clang diagnostic ignored \"-Wswitch\"\n"
        "#elif defined(__GNUC__)\n"
        "    #pragma GCC diagnostic push\n"
        "    #pragma GCC diagnostic ignored \"-Wswitch\"\n"
        "#endif\n");
}

void write_switch_pragma_pop(FILE *f)
{
    fprintf(f,
        "#if defined(__clang__)\n"
        "    #pragma clang diagnostic pop\n"
        "#elif defined(__GNUC__)\n"
        "    #pragma GCC diagnostic pop\n"
        "#endif\n");
}

void collect_all_enums_structs(ProtocolDef *protocols, size_t protocol_count,
    EnumDef **all_enums, size_t *all_enums_count,
    StructDef **all_structs, size_t *all_structs_count)
{
    size_t all_enums_capacity = 0;
    size_t all_structs_capacity = 0;
    StringList enum_names = {0};
    StringList struct_names = {0};

    for (size_t p = 0; p < protocol_count; ++p)
    {
        ProtocolDef *protocol = &protocols[p];
        for (size_t i = 0; i < protocol->enums_count; ++i)
        {
            if (!string_list_contains(&enum_names, protocol->enums[i].name))
            {
                enum_list_push(all_enums, all_enums_count, &all_enums_capacity,
                               &protocol->enums[i]);
                string_list_push(&enum_names, protocol->enums[i].name);
            }
        }
        for (size_t i = 0; i < protocol->structs_count; ++i)
        {
            if (!string_list_contains(&struct_names, protocol->structs[i].name))
            {
                struct_list_push(all_structs, all_structs_count, &all_structs_capacity,
                                 &protocol->structs[i]);
                string_list_push(&struct_names, protocol->structs[i].name);
            }
        }
    }

    string_list_free(&enum_names);
    string_list_free(&struct_names);
}
